### ISSUE TITLE
Payload format to display list

### ISSUE THREAD

**Issue by harshadabhanose** [MishUshakov/dialogflow-web-v2#1]
Hi Mikhail,
Thank you for coming up with this library to support v2 apis.
I am trying this with a sample dialogflow agent that uses `dialogflow-fulfillment-nodejs` library as webhook.
I have some intent handlers that return a payload for `listSelect` for ACTIONS_ON_GOOGLE platform. The sample code looks like below:
```
agent.add(new Payload(agent.ACTIONS_ON_GOOGLE, {
        "expectUserResponse": true,
        "richResponse": {
          "items": [{ "simpleResponse": { "textToSpeech": "Please select an option from below list." } }]
        },
        "systemIntent": {
          "intent": "actions.intent.OPTION",
          "data": {
            "@type": "type.googleapis.com/google.actions.v2.OptionValueSpec",
            "listSelect": {
              "items": [{
                "optionInfo": { "key": "Option1"},
                "title": "Option1"
              },
              {
                "optionInfo": { "key": "Option2" },
                "title": "Option2"
              },
              {
                "optionInfo": { "key": "Option3" },
                "title": "Option3"
              }]
           }
        }
     }
}));

```
However, an empty text response is rendered instead of list.
The `fulfillment[component].platform` in the response in `index.js` of `dialogflow-gateway-master` is returned as `PLATFORM_UNSPECIFIED`.
What should be the platform and format of payload in order to render the list correctly?

**Comment by MishUshakov** [comment]
Hey, I don't think, that there is a way to support fulfilment payloads right now. You can try hacking the dialogflow-gateway, maybe it do it. If so, im waiting for your pull request. Webhook implementation, that Dialogflow provides is really a mess, I don't even know why and how it works.

**Comment by harshadabhanose** [comment]
Thanks for the update Mikhail. Will try it out and request for a pull request if it works :-)
