### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by christianlindauer** [mishushakov/dialogflow-web-v2#10]
How do you change the default language, when accessing the bot? It looks like, that the default language is "en". But we want to change it to "de"

**Comment by mishushakov** [comment]
[`config.js` line 16](https://github.com/mishushakov/dialogflow-web-v2/blob/master/config.js#L16)

**Comment by christianlindauer** [comment]
> 
> 
> [`config.js` line 16](https://github.com/mishushakov/dialogflow-web-v2/blob/master/config.js#L16)

Thanks, that was super fast! Do I need to rebuild it with "npm run build"?
