### ISSUE TITLE
How to send my customer id

### ISSUE THREAD

**Issue by BadChoice** [mishushakov/dialogflow-web-v2#14]
Hi! first of all thank you so much for this project, looks really promising!

I have a question I couldn't find anywhere, I want to run the both in my app, where the user is already logged in, so I would like to get its user id in all the webhooks calls so I know how to filter them, 

is there any way to achieve that?

Thank you!

**Comment by BadChoice** [comment]
I guess this means it is not possible?

**Comment by mishushakov** [comment]
It means you should do it by yourself.
Thanks.

**Comment by BadChoice** [comment]
And do you have any hint where I can start with?


Jordi  Puigdellívol
jordi@gloobus.net

**Comment by mishushakov** [comment]
How should I know?

**Comment by BadChoice** [comment]
hahah
I tought you knew something more about dialogflow that me
I’ll dig further to see if that is something doable

My idea was to send something like ?user_id=my-id in the url so I get that back in the webhook… but don’t know where to start..


Jordi  Puigdellívol
jordi@gloobus.net

**Comment by AmanGarg1707** [comment]
Just set userid as context with lifespan 100 and reset ot every 9 minutes to reset the context so that it will remain for the complete session
