### ISSUE TITLE
Scroll events in iframe also affect parent window

### ISSUE THREAD

**Issue by taosan** [mishushakov/dialogflow-web-v2#15]
There is a problem when using iframe.
When sending a message or selecting it, the parent window will also scroll synchronously.

Is this in the specifications?

sample code http://scratchpad.io/descriptive-can-2849

Thank you,

**Comment by mishushakov** [comment]
It can't happen. Look at the code: https://github.com/mishushakov/dialogflow-web-v2/blob/master/src/Components/App/App.vue#L234-L240

On your link, the page doesn't jump either.
Which browser are you using?

**Comment by taosan** [comment]
@mishushakov Thank you for confirmation

But it happens...
I'll put the information for reference

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36

![issue](https://user-images.githubusercontent.com/5799238/59769486-3706cc00-92e1-11e9-82ac-826ed9f38ef4.gif)

**Comment by mishushakov** [comment]
I'm using latest Safari:

![Screen Recording 2019-06-19 at 16 32 19](https://user-images.githubusercontent.com/10400064/59776400-07d96600-92b3-11e9-8752-5bda919e3fac.gif)

Doesn't jump :D
