### ISSUE TITLE
Agent for project not found.

### ISSUE THREAD

**Issue by JamesAnelay** [mishushakov/dialogflow-web-v2#16]
Would you be able to have a quick look at https://crypto-haven-248819.ui.dialogflow.cloud.ushakov.co & see why it's not working. I get the message "Agent for project 'crypto-haven-248819' not found." but I'm pretty sure ive linked up an agent correctly.

**Comment by mishushakov** [comment]
Hey @JamesAnelay 
This issue tracker is only for Dialogflow for Web v2. For other questions you can contact [here](ushakov.co)

The error "Agent for project 'crypto-haven-248819' not found" comes from Google API, not from Dialogflow Gateway directly.

Are you sure, you have a Dialogflow Agent on your Project?

<img width="717" alt="Screenshot 2019-08-05 at 09 00 57" src="https://user-images.githubusercontent.com/10400064/62445066-aa648000-b75f-11e9-8a8e-002454245fa5.png">

You can ask Google what's going on, if the issue still remains.
