### ISSUE TITLE
How to change speech feedback voice?

### ISSUE THREAD

**Issue by harleygroupmap** [mishushakov/dialogflow-web-v2#17]
Hi

How can we change the voice of the app?

Can it use the standart voice, that was choosen from the list in dialogflow agent settings?
![image](https://user-images.githubusercontent.com/8666032/65986784-3f000b80-e48d-11e9-9166-dfd0f5c6178e.png)

**Comment by mishushakov** [comment]
Hey, the voice comes from WebSpeechAPI, not Dialogflow. You can change it in `config.js`, here:

https://github.com/mishushakov/dialogflow-web-v2/blob/f04af2265a33ea57d7270267104902d87bdaef20/config.js#L9
