### ISSUE TITLE
Speech Feedback Lenth

### ISSUE THREAD

**Issue by harleygroupmap** [mishushakov/dialogflow-web-v2#18]
Hi
We are faced with the problem of limiting the length of the feedback speech. After pronouncing about 200 characters, the bot stops voicing. And then he does not voice the following response messages.

How we can fix it? Maybe there is some setup of speech lenth in project config?

**Comment by mishushakov** [comment]
Hey,
interesting. What browser are you using?

**Comment by harleygroupmap** [comment]
Hi
I use last version of Google Chrome - 77.0.3865.90.

**Comment by harleygroupmap** [comment]
Hi
Do you have any updates?

**Comment by mishushakov** [comment]
Hey, i will investigate into it tomorrow :)
Thanks

**Comment by harleygroupmap** [comment]
Hi.
We investigated the problem - it appears on russian language only.

**Comment by mishushakov** [comment]
Hello again,
sorry for having you wait

I have investigated and it appears, that it's a Chromium-related issue i can barely do something about 🤨
Dialogflow Text to Speech is currently not implemented in the client

Thank you for your patience again and let me know, if you have some work around i could make use of 👍

**Comment by harleygroupmap** [comment]
Hi
We checked some more dialogflow interfaces and fine out that botcopy.com does not have such problem with speach lenth limitation. Seems like they found the way to overcome the problem. Hope that you can find that way too.

**Comment by mishushakov** [comment]
Closing the issue, because it's Chrome-only problem. The rest of browsers should work fine. Thanks for participating
