### ISSUE TITLE
Integrating Dialogflow Web Agent with Actions on Google through Dialogflow Fullfilment

### ISSUE THREAD

**Issue by jerrytohvan** [mishushakov/dialogflow-web-v2#19]
Hi there,
I'm currently been experimenting on dialogflow web v2 agent. So far, I couldn't manage to send back an audio media content attachment as a message response to the web agent via Dialogflow's fullfulment `index.js`

I've tested it on my google assistant running on my google pixel and it worked so I was wondering if you could share with me how to integrate it with the web agent?

Thank you!

**Comment by mishushakov** [comment]
Hey,
thanks for your feedback

I just opened new issue, where we could elaborate more on that topic: #20
