### ISSUE TITLE
Voice Recognition not working

### ISSUE THREAD

**Issue by github-contenta** [MishUshakov/dialogflow-web-v2#2]
Should the Voice Recognition be working? I tap the microphone, but when I speak nothing happens.

Thank you!

**Comment by MishUshakov** [comment]
Which browser and platform are you using? Works for me on macOS and Chrome

**Comment by github-contenta** [comment]
I tested it on Chrome on Android 8. Gateway is running on Ubuntu 18.04. I'll test it on my PC and let you know.

**Comment by github-contenta** [comment]
Maybe the problem is that I'm not serving it over HTTPS? Chrome on my desktop is not letting me allow the microphone. Do you know how to start the development environment over HTTPS?

**Comment by MishUshakov** [comment]
Can you try, if it works on my deployment? 
https://i.ushakov.co/dialogflow-web-v2/

You can then send your console.logs
When you are running on localhost, chrome does not need HTTPS, in other cases it does. Then you can run npm run dev --https --cert <certificate> --key <key>

**Comment by github-contenta** [comment]
Ok, it is working over HTTPS on Desktop. I'm now having a hard time getting it to work on mobile because Chrome refuses to load unsafe scripts there. It does work on your link though, so I guess when I have this on a production environment with the correct certificates it will work too. Thank you.
