### ISSUE TITLE
Reply double up.

### ISSUE THREAD

**Issue by TcFxGt4AGE** [mishushakov/dialogflow-web-v2#23]
Hi, not sure if its just me or not but im always getting the Reply as a double up.
Ive taken a look, but cant quite figure out why it would be doing this.
In google assitant simulator, or Dialogflow i only get the single reply.

![image](https://user-images.githubusercontent.com/11673312/69276881-236ee100-0c44-11ea-9093-fae701601d1f.png)

Cheers

**Comment by mishushakov** [comment]
Change the "Platforms" setting on Dialogflow Gateway
