### ISSUE TITLE
Missing avatars and responses

### ISSUE THREAD

**Issue by WimStienstra** [mishushakov/dialogflow-web-v2#24]
Hello,

I am trying to integrate my dialogflow bot into our website by using one of your applications, but I am running into different problems.

•	I am getting double responses.
•	The bot’s logo is not showing up.
•	Lastly it takes enormously long to get a response and sometimes doesn’t get any response.

I hope you can help me fix these problems or maybe you know what can cause these.

To be clear I tried the df-btn script, dialogflow-web-v2 and the source: https://jipsnel-assistant.ui.dialogflow.cloud.ushakov.co/
(It is a dutch bot tho, so that might give a problem for you to test it?)

**Comment by mishushakov** [comment]
Hey,
i'm here to help

1. Play around with "Platform" setting in Dialogflow Gateway Dashboard
2. I know. Quick fix may be, to change

```html
<img v-if="app.avatarUri" class="app-icon" :alt="app.displayName" :src="app.avatarUri”>
```

to:

```html
<img v-if="app.avatarUri" class="app-icon" :alt="app.displayName" :src=“'https://storage.googleapis.com/cloudprod-apiai/‘ + app.avatarUri”>
```

in `src/Components/Partials/TopHead.vue`

3. Haven't heard of that one yet. Which browser and OS are you using?
Thanks

**Comment by WimStienstra** [comment]
Hello,

Yea the first 2 problems got fixed. Thx, could the icon fix be added as default or?

I am using Windows 10 with Chrome. The response time has been reduced with the 1 response.

**Comment by alasdair-at-flasher** [comment]
I'm seeing issue 3 too. I'm also using Windows 10 with Chrome.

It's like the input is never sent...if I send another question or repeat the initial one, it comes back to life.

I also get frequent "Aw snap" errors from Chrome.

Is there any logging available while running npm run serve?

**Comment by mishushakov** [comment]
Yeah,
let's see what i can do. I could maybe add an option to Dialogflow Gateway, that disables the Realtime backend, the clients will fallback to HTTP instead

**Comment by mishushakov** [comment]
Added the avatars issue to Google's Issue Tracker: https://issuetracker.google.com/issues/147386023

**Comment by mishushakov** [comment]
Avatars fixed, missing responses in progress...

**Comment by mishushakov** [comment]
Temporary fix is to terminate WSS connection on the Client
paste this in the `created()` in `App.vue`:

```js
this.client.wss_connection = null
```

Example on RunKit:

<img width="543" alt="Screenshot 2020-01-27 at 13 01 25" src="https://user-images.githubusercontent.com/10400064/73173344-71510b00-4105-11ea-971a-b94ce50c42a3.png">

**Comment by mishushakov** [comment]
Ok,
i've fixed connection problems, in future versions, Realtime API will be optional, Enterprise Edition also has functionality to disable it server-side 

thanks
