### ISSUE TITLE
getting error using npm run serve command

### ISSUE THREAD

**Issue by athenasaurav** [mishushakov/dialogflow-web-v2#26]
Error: [BABEL] C:\Users\athen\Datascience\Dialogflow Bot\New folder\dialogflow-web-v2-master\src\main.js: Package exports for 'C:\Users\athen\Datascience\Dialogflow Bot\New folder\dialogflow-web-v2-master\node_modules\@babel\helper-compilation-targets' do not define a '.' subpath (While processing: "C:\\Users\\athen\\Datascience\\Dialogflow Bot\\New folder\\dialogflow-web-v2-master\\node_modules\\@vue\\babel-preset-app\\index.js")

How to fix this?

**Comment by mishushakov** [comment]
Definitely works for me
<img width="682" alt="Screenshot 2020-01-25 at 05 23 29" src="https://user-images.githubusercontent.com/10400064/73116221-eae4cf80-3f32-11ea-8774-67c4dd982f4b.png">

I suggest you to delete `node_modules` and re-run `npm i` again
Otherwise maybe try on *nix?
