### ISSUE TITLE
Vue js Native Script

### ISSUE THREAD

**Issue by mariamunze** [mishushakov/dialogflow-web-v2#28]
Hi Mishushakov,
thank you for your great work. I just started playing around with your web interface and I really like it. I'm just wondering if you can commit a native version of your work. As far as I've read, by using Vuejs Native script library it involves a couple of changes in a couple of lines to turn your web interface into an android or iOS app. But when I try, I face a package conflict.
This is not an issue but rather a suggestion. If you could add this option would be amazing.

**Comment by mishushakov** [comment]
Native clients can use WebViews
Dialogflow for Web is for Web, obviously

thanks for the suggestion though
