### ISSUE TITLE
Dump question, gateway URL?

### ISSUE THREAD

**Issue by djhomeless** [MishUshakov/dialogflow-web-v2#3]
Where do you find the gateway URL? I've primarily been testing via Slack and WhatsApp so this is my first attempt at using a chat UI like this. In my console I can see my project ID, my API key, etc, but no clue where I would find the gateway URL. 

Sorry I did try and rtfm via the docs on Dialogflow but no help.

**Comment by MishUshakov** [comment]
Hey, don't worry, I will help you!
Please read the documentation in this repository first. For at least 3 times it states, that you need to install [Dialogflow Gateway](https://github.com/MishUshakov/dialogflow-gateway).

The Gateway is my another product and is not associated with Dialogflow Product in any other ways, rather then consuming it's API.

I hope, you can find more answers to your questions in the Gateway repository and understand the way things work here. If you have any other questions and doubts, feel free to leave your comment here.

Thank you for using my Product! And happy valentines day to you and your loved ones! Thank you.

**Comment by djhomeless** [comment]
Ahh, for some stupid reason I thought this was a Dialogflow component - was feverishly reading their docs not yours. Sorry.
