### ISSUE TITLE
record icon is not working in safar, mozilla, edge etc.

### ISSUE THREAD

**Issue by muhammadowaiswarsi** [mishushakov/dialogflow-web-v2#30]
web app voice recognition is just working in google chrome. What should do for that?

**Comment by mishushakov** [comment]
It works on Firefox and should work on new Edge
on other browsers like Safari its not even displayed:

<img width="1376" alt="Screenshot 2020-02-07 at 22 57 50" src="https://user-images.githubusercontent.com/10400064/74068966-46b45b80-49fd-11ea-9d9c-c5ca262abba6.png">

If you want to support more browsers, make audio recording and send it directly to Dialogflow

**Comment by muhammadowaiswarsi** [comment]
just see it shows arrow icon and not working

**Comment by mishushakov** [comment]
So, what did you expect? What's not working?

**Comment by muhammadowaiswarsi** [comment]
![Inked74068966-46b45b80-49fd-11ea-9d9c-c5ca262abba6_LI](https://user-images.githubusercontent.com/26751274/74069206-5cd31380-4a1f-11ea-87c0-b672bdbdeaee.jpg)

**Comment by mishushakov** [comment]
See browser support table: https://caniuse.com/#search=speech%20recognition%20api
I can't do anything, if your browser isn't supported ¯\_(ツ)_/¯

**Comment by muhammadowaiswarsi** [comment]
my mozilla is updated, version : "72.0.2 (64-bit)"

**Comment by mishushakov** [comment]
Sorry, my mistake
mozilla isn't supported either 😭
i will try to support voice input with MediaRecorder API, which is more supported (see #31)

**Comment by muhammadowaiswarsi** [comment]
yes sure please and also not supported in safari and microsoft edge
