### ISSUE TITLE
Add audio input for unsupported browsers

### ISSUE THREAD

**Issue by mishushakov** [mishushakov/dialogflow-web-v2#31]
To fix #30 allow to record audio and send it to Dialogflow 👌

**Comment by muhammadowaiswarsi** [comment]
Hello @mishushakov what you think, How many time this issue will required?

**Comment by mishushakov** [comment]
Hey, i have it working, so probably tomorrow :)

**Comment by muhammadowaiswarsi** [comment]
> Hey, i have it working, so probably tomorrow :)

Thanks

**Comment by mishushakov** [comment]
Here a sneak peek: https://drive.google.com/file/d/1RBzzUb1IgsDArL4ecxkq4TH9NI_zeE6C/view?usp=sharing

**Comment by muhammadowaiswarsi** [comment]
looking good Thanks, I am waiting for it :)
