### ISSUE TITLE
Knowledge Base Support

### ISSUE THREAD

**Issue by deadmantfa** [mishushakov/dialogflow-web-v2#32]
Hi @mishushakov ,

First thing first, This is an awesome project, thank you.

Now for the issue, I have create a DialogFlow Agent to support the knowledge base provided by dialog flow. 

I followed the steps mentioned and it does respond back to the small talk options but knowledge base its not responding to the question.

I was wondering if that is supported by this project or is there something I am missing

https://cloud.google.com/dialogflow/docs/knowledge-connectors

Regards,
Wenceslaus Dsilva

**Comment by mishushakov** [comment]
Hey,
will do when its out of beta
thanks

**Comment by deadmantfa** [comment]
Thank you @mishushakov is there a way I can test it using this project as we are still building.

**Comment by mishushakov** [comment]
You could make a fork and try to implement it yourself with the existing components
if it's cool, feel free to make a pull request ;)

**Comment by deadmantfa** [comment]
So I just checked Dialog flow blog and it mentioned something abot a mega agent and I tried it. Which now responds to knowledge base questions without making any changes to your code.

**Comment by deadmantfa** [comment]
> You could make a fork and try to implement it yourself with the existing components
> if it's cool, feel free to make a pull request ;)

I will try and see if I can make something.

**Comment by mishushakov** [comment]
that's great news! Thank you

**Comment by valgaze** [comment]
@deadmantfa 
 
From this thread I gather you couldn't get a response from Knowledge Connector/Knowledge Base, correct?

My understanding is that Knowledge Connectors really aren't at all treated differently than a "normal" static intent. You ingest an FAQ or some kind of semi-structured knowledge document and each question/response becomes a bit of a mini-intent of question/answer usually just text.

When it wasn't working, was it also failing in the simulator?

My instinct is that this lib wouldn't be at all related to something like that (more DF config issue) but if you were doing unusual with Knowledge Connectors I'm curious!

**Comment by mishushakov** [comment]
Hey gentlemen,
so, i've tested it myself

Knowledge Connectors do indeed work with Dialogflow for Web
but Dialogflow Gateway Hosted has no support for beta/experimental Dialogflow features

if you want to support the Knowledge Connectors right now, you can either purchase the Enterprise Edition of Dialogflow Gateway or try to implement it yourself

Thank you very much, i will keep the issue opened so others could see

**Comment by deadmantfa** [comment]
@mishushakov @valgaze I got it to work by simply creating a Mega Agent and adding my FAQ knowledge base agent as a sub-agent and all worked well. Did not need to do much. I think we can close this issue. If you want I can share the url if you want to test it out.

**Comment by mishushakov** [comment]
Sure, but that's more like a hack
the real reason, i explained above: https://github.com/mishushakov/dialogflow-web-v2/issues/32#issuecomment-590051958

thanks
