### ISSUE TITLE
Freeze chat input form when suggestion button comes out.

### ISSUE THREAD

**Issue by mariamunze** [mishushakov/dialogflow-web-v2#33]
Hey @mishushakov , I noticed that the chat input form can still send inputs although suggestion buttons pop up. This might break the flow as the user is free of inputting whatever he wants and might not press any suggestion. Is there a way I can implement a form freezing up to the point the user presses the suggestion?

**Comment by mishushakov** [comment]
Hey, the behavior is correct. Suggestion is just a suggestion, but if you want to offer your users a choice, i advise you to use a List. Otherwise you can require slots for your intent, so the user can not proceed without giving a correct answer

thanks
