### ISSUE TITLE
Time of transcription

### ISSUE THREAD

**Issue by nfrn** [mishushakov/dialogflow-web-v2#36]
Hello.
First, thank you for your awesome work, very useful.

When running the app, when using the mic to communicate, often when the input sentence is long, the Speech-to-Text stops in the middle of my sentence, when there are silence periods between words.

I was wondering if there is a parameter or config, that can make the STT ignore short silence periods and only end the transcription when the silence is longer than N seconds.

Thank you for your time,

Nelson

**Comment by mishushakov** [comment]
Hey,
i'm afraid this is not possible
it's the STT service, which decides when to stop listening

you could however, try to change this

https://github.com/mishushakov/dialogflow-web-v2/blob/90e7b03da92c4ff985092cb8a997f6af8f7c8efb/src/Components/Parts/ChatInput.vue#L133

to `onspeechend` or `onaudioend`

thanks
