### ISSUE TITLE
IAM permission 'dialogflow.agents.get' on 'projects/small-talk-hqbbmy' denied.

### ISSUE THREAD

**Issue by the-portalboy** [mishushakov/dialogflow-web-v2#37]
IAM permission 'dialogflow.agents.get' on 'projects/small-talk-hqbbmy' denied.

**Comment by mishushakov** [comment]
hey, please see: https://github.com/mishushakov/dialogflow-gateway-docs/blob/master/hosted/installation.md

thanks
