### ISSUE TITLE
The deployment was not found

### ISSUE THREAD

**Issue by ai4publicservices** [mishushakov/dialogflow-web-v2#41]
"
![Capture](https://user-images.githubusercontent.com/69250885/89423107-b5822f80-d768-11ea-9be9-f17b4bd3acb5.PNG)
The deployment was not found" appears when I try to run the Web using run serve. I'm using my own Dialogflow agent for the gateway.

**Comment by ai4publicservices** [comment]
I tried deploying in firebase but it has the same error message on the chat widget

**Comment by mishushakov** [comment]
have you connected it to the gateway?

**Comment by ai4publicservices** [comment]
Yes. because when I send a query to the bot, it replies correctly. Then the error message was gone.

But when I refresh the page. The error will be back along with the previous conversation I made with the bot.

Attached is the image when I refreshed the page and error is back.

![Capture](https://user-images.githubusercontent.com/69250885/89426364-abfac680-d76c-11ea-84ce-7483e697a0a3.PNG)

**Comment by ai4publicservices** [comment]
Right now I'm testing it using the Web UI from Gateway console.

https://socialproblem1-spvd.web.ushaflow.io/

**Comment by mishushakov** [comment]
then your gateway URL is https://socialproblem1-spvd.core.ushaflow.io
should work 👍

**Comment by ai4publicservices** [comment]
Yes, I'm using that gateway URL. But the thing is even if I check it on the Web UI (https://socialproblem1-spvd.web.ushaflow.io/) which I got from Gateway Console, the error "The deployment was not found" is also there. 

If I talk to the bot from Gateway Console, the error will gone but If I refresh the page, It'll be back again.

**Comment by mishushakov** [comment]
works for me, maybe clean your cache/cookies?

**Comment by ai4publicservices** [comment]
Gee! Thanks! It worked!
