### ISSUE TITLE
Missing Avatar on Web Demo (Agent icon)

### ISSUE THREAD

**Issue by vonmoraes** [mishushakov/dialogflow-web-v2#45]
I select an image for be the avatar for my agent but this image not showing. 

Using the web demo link the image is showing like this: 
![opera_pDlI37BIlW](https://user-images.githubusercontent.com/31371849/91669542-0da01d80-eaec-11ea-8fbb-9e6868d5adad.png)

the image in only a .png and i tried to change with another file but i had no success

**Comment by mishushakov** [comment]
Hey,
please ask Dialogflow at support@dialogflow.com
or open an issue: https://issuetracker.google.com/issues?q=componentid:501190%20status:open

thanks
