### ISSUE TITLE
Text to Speech not working chrome browser.

### ISSUE THREAD

**Issue by ezoomdev** [mishushakov/dialogflow-web-v2#9]
Installed dialogflow-web-v2 with the instructions given and it is successfully runs on development. 
But voice works with firefox and not with chrome.

**Comment by mishushakov** [comment]
Check your HTTPS certificate

**Comment by malikasinger1** [comment]
is it working in safari mobile and safari mac?

**Comment by mishushakov** [comment]
Hey, T2S is working on Safari on Mac, but not on iPhone/iPad as far as I know.
Thanks.

**Comment by hostandname** [comment]
any solution for this yet? see this was raised a long time ago now but im finding from new setup, mic is working fine but the responses are just text and no audio.... iphone devices on safari / prob any ios mobile / tablet device but not tested. works fine with macbook safari.

**Comment by mishushakov** [comment]
Hello, try enabling "Automatic Text to Speech" in your agent's settings
or purchase Enterprise Edition Gateway - it has SSML
